/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServantRouteImport } from './routes/servant'
import { Route as ServantRegisterSecret89xqRouteImport } from './routes/servant-register-secret-89xq'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteImport } from './routes/student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServantRoute = ServantRouteImport.update({
  id: '/servant',
  path: '/servant',
  getParentRoute: () => rootRouteImport,
} as any)
const ServantRegisterSecret89xqRoute =
  ServantRegisterSecret89xqRouteImport.update({
    id: '/servant-register-secret-89xq',
    path: '/servant-register-secret-89xq',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servant': typeof ServantRoute
  '/servant-register-secret-89xq': typeof ServantRegisterSecret89xqRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servant': typeof ServantRoute
  '/servant-register-secret-89xq': typeof ServantRegisterSecret89xqRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servant': typeof ServantRoute
  '/servant-register-secret-89xq': typeof ServantRegisterSecret89xqRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/servant'
    | '/servant-register-secret-89xq'
    | '/signup'
    | '/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/servant'
    | '/servant-register-secret-89xq'
    | '/signup'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/servant'
    | '/servant-register-secret-89xq'
    | '/signup'
    | '/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ServantRoute: typeof ServantRoute
  ServantRegisterSecret89xqRoute: typeof ServantRegisterSecret89xqRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servant': {
      id: '/servant'
      path: '/servant'
      fullPath: '/servant'
      preLoaderRoute: typeof ServantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servant-register-secret-89xq': {
      id: '/servant-register-secret-89xq'
      path: '/servant-register-secret-89xq'
      fullPath: '/servant-register-secret-89xq'
      preLoaderRoute: typeof ServantRegisterSecret89xqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ServantRoute: ServantRoute,
  ServantRegisterSecret89xqRoute: ServantRegisterSecret89xqRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
